name: e2e Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        architecture: ["x64"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.architecture }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install ffmpeg

      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Gr1N/setup-poetry@v7
      - uses: actions/cache@v3
        id: poetry-cache
        with:
          path: |
            **/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: e2e without subprocess
        run: |
          poetry run yutto -v
          poetry run yutto -h
          poetry run yutto https://www.bilibili.com/video/BV1AZ4y147Yg -w
          just clean

      - name: e2e test
        run: |
          poetry run pytest -m "e2e and not (ci_skip or ignore)" --workers auto
