name: e2e Test

on:
  push:
    branches: [main]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        architecture: ["x64"]
    name: Python ${{ matrix.python-version }} on ${{ matrix.architecture }} e2e test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
          cache: "poetry"

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install ffmpeg

      - name: Install just
        uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          poetry install

      - name: e2e without subprocess
        run: |
          poetry run yutto -v
          poetry run yutto -h
          poetry run yutto https://www.bilibili.com/video/BV1AZ4y147Yg -w
          just clean

      - name: e2e test
        run: |
          just ci-e2e-test
